### ISSUE TITLE
-e can only be used once

### ISSUE THREAD

**Issue by aidanbh** [PenguinSnail/Quick-Back#20]

**Comment by aidanbh** [comment]
Working on this now...

...in bithakr-patch-multiexclude branch

**Comment by aidanbh** [comment]
@PenguinSnail can you look at my code and see if there are any obvious syntax errors? I'm a little rusty on all the bash expansion codes

**Comment by PenguinSnail** [comment]
@bithakr from what I understand the code appears as if it should function properly, but whenever I run it the excludes don't work even if using only one exclude.

If I understand correctly, we are adding file paths as strings in an array, then adding the `--exclude=` text in the front of each and then appending that to the rsync command?

**Comment by PenguinSnail** [comment]
Ok changes have been made it appears to work on my system, so moving this issue to awaiting review for it to be checked. Changes are in the bithakr-patch-multiexclude branch.

**Comment by aidanbh** [comment]
@PenguinSnail testing now...

**Comment by aidanbh** [comment]
Works! closing and merging...

**Comment by aidanbh** [comment]
#31 merged to master, conflict with changes from #28 resolved
