### ISSUE TITLE
[toolchain] Get some CI working

### ISSUE THREAD

**Issue by aidanbh** [PenguinSnail/Quick-Back#29]
Travis sudo-enabled builds might work but we need to generate some sort of ramdisk, emulated fs, etc. for testing, otherwise we'll have to use the `--force-ignore` option to backup b/w two normal dirs.

**Comment by aidanbh** [comment]
Researching options now..

**Comment by aidanbh** [comment]
`losetup` might work..

**Comment by PenguinSnail** [comment]
Closing for now - ShellCheck on Travis enabled. Still need to really test.
